version: "2"

services:

### Databases Data Container ####################

  volumes_data:
    container_name: volumes_data
    build: ./volumes_data
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/redis:/data
      - ./data/memcached:/var/lib/memcached

### MySql Container #############################

  mysql:
    container_name: mysql
    image: mysql
    volumes_from:
      - volumes_data
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123

### PostgreSQL Container ########################

  postgres:
    container_name: postgres
    image: postgres
    volumes_from:
      - volumes_data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test123

### Redis Container #########################################

  redis:
    container_name: redis
    image: redis
    volumes_from:
      - volumes_data
    ports:
      - "6379:6379"

### Memcached Container #####################################

  memcached:
    container_name: memcached
    image: memcached
    volumes_from:
      - volumes_data
    ports:
      - "11211:11211"
