version: "3.7"

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql57:/var/lib/mysql

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11211:11211"

  minio:
    container_name: minio
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ""
      MINIO_SECRET_KEY: ""
    ports:
      - "9000:9000"
    volumes:
      - ./data/minio:/data

