version: "3.7"

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - ./data/mariadb:/var/lib/mysql

  mysql:
    container_name: mysql
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - ./data/mysql:/var/lib/mysql

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11211:11211"
