version: "2"

services:

### Databases Data Container ####################

  data:
    container_name: data
    build: ./data
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/lib/redis:/data

### MySql Container #############################

  mysql:
    container_name: mysql
    image: mysql
    volumes_from:
      - data
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123

### Redis Container #########################################

  redis:
    container_name: redis
    image: redis
    volumes_from:
        - data
    ports:
        - "6379:6379"
